# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "remix-rails-app"
client_id = "15377aa442ab0af560c0be6464e2e470"
application_url = "https://zshops-ist-wheat-sleeve.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://zshops-ist-wheat-sleeve.trycloudflare.com/auth/callback",
  "https://zshops-ist-wheat-sleeve.trycloudflare.com/auth/shopify/callback",
  "https://zshops-ist-wheat-sleeve.trycloudflare.com/api/auth/callback",
  "https://zshops-ist-wheat-sleeve.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ongraph-store121.myshopify.com"
